// Package schema provides schema definition and metadata structures for the ORM.
package schema

import "reflect"

// EnumType represents a PostgreSQL ENUM type.
type EnumType struct {
	Name   string   // PostgreSQL enum type name (e.g., "order_status")
	Values []string // Enum values in order (e.g., ["pending", "active", "completed"])
}

// TableMetadata represents a database table with all its metadata.
type TableMetadata struct {
	Name          string                 // Table name in database
	GoType        reflect.Type           // Go struct type
	Columns       []ColumnMetadata       // Table columns
	PrimaryKey    *PrimaryKeyMetadata    // Primary key definition
	ForeignKeys   []ForeignKeyMetadata   // Foreign key constraints
	Indexes       []IndexMetadata        // Table indexes
	Constraints   []ConstraintMetadata   // Additional constraints
	Relationships []RelationshipMetadata // Relationships to other tables
	EnumTypes     []EnumType             // Enum types used by this table
	Comment       string                 // Table comment
}

// ColumnMetadata represents a single column in a table.
type ColumnMetadata struct {
	Name          string           // Column name in database
	GoField       string           // Go struct field name
	GoType        reflect.Type     // Go field type
	SQLType       string           // PostgreSQL type (e.g., "varchar(255)", "uuid")
	Nullable      bool             // Can column be NULL
	Default       *string          // Default value expression
	Unique        bool             // UNIQUE constraint
	AutoIncrement bool             // AUTO_INCREMENT / SERIAL (legacy)
	Identity      *IdentityColumn  // Identity column definition (nil if not identity) - PostgreSQL 10+
	Comment       string           // Column comment
	Position      int              // Column position in struct
	Generated     *GeneratedColumn // Generated column definition (nil if not generated)
	EnumType      string           // PostgreSQL enum type name (e.g., "order_status"), empty if not enum
	EnumValues    []string         // Enum values for this column (if enum type)
}

// IdentityColumn represents a PostgreSQL identity column (GENERATED AS IDENTITY).
// This is the modern SQL standard way to create auto-incrementing columns.
// Introduced in PostgreSQL 10, recommended over SERIAL.
type IdentityColumn struct {
	Generation IdentityGeneration // ALWAYS or BY DEFAULT
}

// IdentityGeneration specifies when identity values are generated.
type IdentityGeneration string

const (
	// IdentityAlways means values are always generated, user cannot override.
	// INSERT must use OVERRIDING SYSTEM VALUE to provide explicit values.
	IdentityAlways IdentityGeneration = "ALWAYS"

	// IdentityByDefault means values are generated by default, but user can override.
	// Similar to DEFAULT behavior but uses identity mechanism.
	IdentityByDefault IdentityGeneration = "BY DEFAULT"
)

// GeneratedColumn represents a PostgreSQL generated column.
type GeneratedColumn struct {
	Expression string         // SQL expression for the generated value
	Type       GenerationType // STORED or VIRTUAL
}

// GenerationType specifies how a generated column is computed.
type GenerationType string

const (
	// GeneratedStored means the column is computed on INSERT/UPDATE and stored in the table.
	GeneratedStored GenerationType = "STORED"

	// GeneratedVirtual means the column is computed on read (PostgreSQL 12+).
	// Note: PostgreSQL currently only supports STORED, but VIRTUAL is reserved for future use.
	GeneratedVirtual GenerationType = "VIRTUAL"
)

// PrimaryKeyMetadata represents a primary key constraint.
type PrimaryKeyMetadata struct {
	Columns []string // Column names in the primary key
	Name    string   // Constraint name (e.g., "users_pkey")
}

// ForeignKeyMetadata represents a foreign key constraint.
type ForeignKeyMetadata struct {
	Name              string          // Constraint name
	Columns           []string        // Local column names
	ReferencedTable   string          // Referenced table name
	ReferencedColumns []string        // Referenced column names
	OnDelete          ReferenceAction // ON DELETE action
	OnUpdate          ReferenceAction // ON UPDATE action
}

// IndexMetadata represents a database index.
type IndexMetadata struct {
	Name    string   // Index name
	Columns []string // Indexed columns
	Unique  bool     // UNIQUE index
	Type    string   // Index type (btree, hash, gin, etc.)
}

// ConstraintMetadata represents additional constraints (CHECK, UNIQUE, etc.).
type ConstraintMetadata struct {
	Name       string         // Constraint name
	Type       ConstraintType // Constraint type
	Expression string         // CHECK expression or other definition
	Columns    []string       // Column names for UNIQUE/PRIMARY/FOREIGN constraints
}

// RelationshipMetadata represents relationships between tables.
type RelationshipMetadata struct {
	Type         RelationType // Relationship type
	SourceTable  string       // Source table name
	SourceField  string       // Source Go field name
	TargetTable  string       // Target table name (derived, may be incorrect if custom table name)
	TargetType   reflect.Type // Target Go type (used for accurate table name lookup)
	TargetField  string       // Target Go field name
	ForeignKey   string       // Foreign key column
	References   string       // Referenced column
	JoinTable    *string      // Junction table for many-to-many
	InverseField *string      // Inverse relationship field
}

// RelationType defines the type of relationship between tables.
type RelationType string

const (
	// BelongsTo represents a many-to-one relationship.
	BelongsTo RelationType = "belongsTo"
	// HasOne represents a one-to-one relationship.
	HasOne RelationType = "hasOne"
	// HasMany represents a one-to-many relationship.
	HasMany RelationType = "hasMany"
	// ManyToMany represents a many-to-many relationship.
	ManyToMany RelationType = "manyToMany"
)

// ReferenceAction defines the action for foreign key constraints.
type ReferenceAction string

const (
	// NoAction means no action on referenced row changes.
	NoAction ReferenceAction = "NO ACTION"
	// Restrict prevents referenced row changes.
	Restrict ReferenceAction = "RESTRICT"
	// Cascade propagates changes to referencing rows.
	Cascade ReferenceAction = "CASCADE"
	// SetNull sets referencing columns to NULL.
	SetNull ReferenceAction = "SET NULL"
	// SetDefault sets referencing columns to their default values.
	SetDefault ReferenceAction = "SET DEFAULT"
)

// ConstraintType defines the type of constraint.
type ConstraintType string

const (
	// CheckConstraint represents a CHECK constraint.
	CheckConstraint ConstraintType = "CHECK"
	// UniqueConstraint represents a UNIQUE constraint.
	UniqueConstraint ConstraintType = "UNIQUE"
	// ExclusionConstraint represents an EXCLUDE constraint.
	ExclusionConstraint ConstraintType = "EXCLUDE"
)

// GetColumnByName returns a column by its database name.
func (t *TableMetadata) GetColumnByName(name string) *ColumnMetadata {
	for i := range t.Columns {
		if t.Columns[i].Name == name {
			return &t.Columns[i]
		}
	}
	return nil
}

// GetColumnByField returns a column by its Go field name.
func (t *TableMetadata) GetColumnByField(field string) *ColumnMetadata {
	for i := range t.Columns {
		if t.Columns[i].GoField == field {
			return &t.Columns[i]
		}
	}
	return nil
}

// PrimaryKeyColumns returns the names of primary key columns.
func (t *TableMetadata) PrimaryKeyColumns() []string {
	if t.PrimaryKey == nil {
		return nil
	}
	return t.PrimaryKey.Columns
}

// IsPrimaryKey checks if a column is part of the primary key.
func (t *TableMetadata) IsPrimaryKey(columnName string) bool {
	if t.PrimaryKey == nil {
		return false
	}
	for _, col := range t.PrimaryKey.Columns {
		if col == columnName {
			return true
		}
	}
	return false
}
