version: 2

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  disable:
    - goconst
    - gocyclo
    - gosec

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - (*database/sql.Rows).Close
      - (*database/sql.Tx).Rollback

issues:
  exclude-dirs:
    - examples
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
