version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: pebble
    main: ./cmd/pebble
    binary: pebble
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: pebble-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Other Changes
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"
      - "go mod tidy"

release:
  github:
    owner: marshallshelly
    name: pebble-orm
  draft: false
  prerelease: auto

brews:
  - name: pebble
    repository:
      owner: marshallshelly
      name: homebrew-tap
    homepage: https://github.com/marshallshelly/pebble-orm
    description: Type-safe PostgreSQL ORM for Go. Compile-time safety, runtime speed.
    license: MIT
    install: |
      bin.install "pebble"
