// Code generated by pebble-orm. DO NOT EDIT.
// pebble generate metadata --scan ./internal/models

package models

import "github.com/marshallshelly/pebble-orm/pkg/schema"

func init() {
	// Register custom table names from comment directives
	schema.RegisterTableName("Document", "documents")
	schema.RegisterTableName("Location", "locations")
	schema.RegisterTableName("Product", "products")
	schema.RegisterTableName("Schedule", "schedules")
}
