// Code generated by pebble-orm. DO NOT EDIT.
// pebble generate metadata --scan ./internal/models

package models

import "github.com/marshallshelly/pebble-orm/pkg/schema"

func init() {
	// Register custom table names from comment directives
	schema.RegisterTableName("Author", "authors")
	schema.RegisterTableName("Book", "books")
	schema.RegisterTableName("Profile", "profiles")
	schema.RegisterTableName("Role", "roles")
	schema.RegisterTableName("User", "users")
	schema.RegisterTableName("UserRole", "user_roles")
}
