// Code generated by pebble-orm. DO NOT EDIT.
// pebble generate metadata --scan ./internal/models

package models

import "github.com/marshallshelly/pebble-orm/pkg/schema"

func init() {
	// Register custom table names from comment directives
	schema.RegisterTableName("APIKey", "api_keys")
	schema.RegisterTableName("AnalyticsEvent", "analytics_events")
	schema.RegisterTableName("Article", "articles")
	schema.RegisterTableName("Document", "documents")
	schema.RegisterTableName("Event", "events")
	schema.RegisterTableName("InternationalProduct", "international_products")
	schema.RegisterTableName("Order", "orders")
	schema.RegisterTableName("Product", "products")
	schema.RegisterTableName("SearchTerm", "search_terms")
	schema.RegisterTableName("SensorReading", "sensor_readings")
	schema.RegisterTableName("Task", "tasks")
	schema.RegisterTableName("User", "users")
}
