package main

import (
	"context"
	"log"

	"github.com/marshallshelly/pebble-orm/examples/identity-columns/internal/database"
	"github.com/marshallshelly/pebble-orm/examples/identity-columns/internal/models"
	"github.com/marshallshelly/pebble-orm/pkg/builder"
)

func main() {
	ctx := context.Background()

	// Initialize database connection
	qb, cleanup, err := database.Initialize(ctx)
	if err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}
	defer cleanup()

	log.Println("=== Pebble ORM Identity Columns Example ===")

	// Example 1: INSERT Product with GENERATED ALWAYS AS IDENTITY
	log.Println("\n--- Example 1: INSERT Product (GENERATED ALWAYS) ---")
	newProduct := models.Product{
		Name:        "Premium Widget",
		Description: "A high-quality widget with advanced features",
		Price:       49.99,
		InStock:     true,
	}

	insertedProducts, err := builder.Insert[models.Product](qb).
		Values(newProduct).
		Returning(
			builder.Col[models.Product]("ID"),
			builder.Col[models.Product]("Name"),
			builder.Col[models.Product]("Price"),
		).
		ExecReturning(ctx)
	if err != nil {
		log.Printf("Insert product failed: %v", err)
	} else {
		log.Printf("✅ Inserted product: ID=%d, Name=%s, Price=%.2f",
			insertedProducts[0].ID, insertedProducts[0].Name, insertedProducts[0].Price)
	}

	// Example 2: INSERT Order with GENERATED BY DEFAULT AS IDENTITY
	log.Println("\n--- Example 2: INSERT Order (GENERATED BY DEFAULT) ---")
	if len(insertedProducts) > 0 {
		newOrder := models.Order{
			OrderNumber: "ORD-2025-001",
			ProductID:   insertedProducts[0].ID,
			Quantity:    2,
			TotalPrice:  99.98,
			Status:      "pending",
		}

		insertedOrders, err := builder.Insert[models.Order](qb).
			Values(newOrder).
			Returning(
				builder.Col[models.Order]("ID"),
				builder.Col[models.Order]("OrderNumber"),
				builder.Col[models.Order]("TotalPrice"),
			).
			ExecReturning(ctx)
		if err != nil {
			log.Printf("Insert order failed: %v", err)
		} else {
			log.Printf("✅ Inserted order: ID=%d, OrderNumber=%s, Total=%.2f",
				insertedOrders[0].ID, insertedOrders[0].OrderNumber, insertedOrders[0].TotalPrice)
		}
	}

	// Example 3: INSERT Customer with legacy SERIAL
	log.Println("\n--- Example 3: INSERT Customer (Legacy SERIAL) ---")
	newCustomer := models.Customer{
		Email: "john.doe@example.com",
		Name:  "John Doe",
	}

	insertedCustomers, err := builder.Insert[models.Customer](qb).
		Values(newCustomer).
		Returning(
			builder.Col[models.Customer]("ID"),
			builder.Col[models.Customer]("Email"),
			builder.Col[models.Customer]("Name"),
		).
		ExecReturning(ctx)
	if err != nil {
		log.Printf("Insert customer failed: %v", err)
	} else {
		log.Printf("✅ Inserted customer: ID=%d, Email=%s",
			insertedCustomers[0].ID, insertedCustomers[0].Email)
	}

	// Example 4: SELECT Products
	log.Println("\n--- Example 4: SELECT Products ---")
	products, err := builder.Select[models.Product](qb).
		OrderByDesc(builder.Col[models.Product]("CreatedAt")).
		All(ctx)
	if err != nil {
		log.Printf("Select products failed: %v", err)
	} else {
		log.Printf("Found %d product(s):", len(products))
		for _, p := range products {
			log.Printf("  - ID=%d: %s ($%.2f)", p.ID, p.Name, p.Price)
		}
	}

	// Example 5: SELECT Orders
	log.Println("\n--- Example 5: SELECT Orders ---")
	orders, err := builder.Select[models.Order](qb).
		OrderByDesc(builder.Col[models.Order]("CreatedAt")).
		All(ctx)
	if err != nil {
		log.Printf("Select orders failed: %v", err)
	} else {
		log.Printf("Found %d order(s):", len(orders))
		for _, o := range orders {
			log.Printf("  - ID=%d: %s (Status: %s, Total: $%.2f)",
				o.ID, o.OrderNumber, o.Status, o.TotalPrice)
		}
	}

	// Example 6: UPDATE Order status
	log.Println("\n--- Example 6: UPDATE Order Status ---")
	if len(orders) > 0 {
		count, err := builder.Update[models.Order](qb).
			Set(builder.Col[models.Order]("Status"), "shipped").
			Where(builder.Eq(builder.Col[models.Order]("OrderNumber"), "ORD-2025-001")).
			Exec(ctx)
		if err != nil {
			log.Printf("Update failed: %v", err)
		} else {
			log.Printf("✅ Updated %d order(s) to 'shipped' status", count)
		}
	}

	// Example 7: COUNT Products
	log.Println("\n--- Example 7: COUNT Products ---")
	productCount, err := builder.Select[models.Product](qb).
		Where(builder.Eq(builder.Col[models.Product]("InStock"), true)).
		Count(ctx)
	if err != nil {
		log.Printf("Count failed: %v", err)
	} else {
		log.Printf("✅ Total in-stock products: %d", productCount)
	}

	log.Println("\n=== Examples Complete ===")
	log.Println("\n💡 Key Differences:")
	log.Println("   • Product.ID: GENERATED ALWAYS AS IDENTITY (strict, best practice)")
	log.Println("   • Order.ID: GENERATED BY DEFAULT AS IDENTITY (flexible)")
	log.Println("   • Customer.ID: SERIAL (legacy, still supported)")
}
