// Code generated by pebble-orm. DO NOT EDIT.
// pebble generate metadata --scan ./internal/models

package models

import "github.com/marshallshelly/pebble-orm/pkg/schema"

func init() {
	// Register custom table names from comment directives
	schema.RegisterTableName("AuditLog", "audit_logs")
	schema.RegisterTableName("DataExportRequest", "data_export_requests")
	schema.RegisterTableName("DeletionRequest", "deletion_requests")
	schema.RegisterTableName("Document", "documents")
	schema.RegisterTableName("Tenant", "tenants")
	schema.RegisterTableName("User", "users")
}
