package models

import "time"

// Product demonstrates GENERATED ALWAYS AS IDENTITY (recommended)
// The ID column will always be auto-generated.
type Product struct {
	ID          int64     `po:"id,primaryKey,bigint,identity"`
	Name        string    `po:"name,varchar(255),notNull"`
	Description string    `po:"description,text"`
	Price       float64   `po:"price,numeric(10,2),notNull"`
	InStock     bool      `po:"in_stock,boolean,default(true),notNull"`
	CreatedAt   time.Time `po:"created_at,timestamptz,default(NOW()),notNull"`
	UpdatedAt   time.Time `po:"updated_at,timestamptz,default(NOW()),notNull"`
}

// Order demonstrates GENERATED BY DEFAULT AS IDENTITY
// The ID column is auto-generated by default, but can be manually overridden when needed.
type Order struct {
	ID          int       `po:"id,primaryKey,integer,identityByDefault"`
	OrderNumber string    `po:"order_number,varchar(50),unique,notNull"`
	ProductID   int64     `po:"product_id,bigint,notNull"`
	Quantity    int       `po:"quantity,integer,notNull"`
	TotalPrice  float64   `po:"total_price,numeric(10,2),notNull"`
	Status      string    `po:"status,varchar(20),default('pending'),notNull"`
	CreatedAt   time.Time `po:"created_at,timestamptz,default(NOW()),notNull"`

	// Relationship
	Product *Product `po:"-,belongsTo,foreignKey(product_id),references(id)"`
}
