// Code generated by pebble-orm. DO NOT EDIT.
// pebble generate metadata --scan ./internal/models

package models

import "github.com/marshallshelly/pebble-orm/pkg/schema"

func init() {
	// Register custom table names from comment directives
	schema.RegisterTableName("Category", "categories")
	schema.RegisterTableName("Comment", "comments")
	schema.RegisterTableName("Post", "posts")
	schema.RegisterTableName("Product", "products")
	schema.RegisterTableName("User", "users")
}
